$(document).ready(function(){
    $('.food-slider').slick({
        autoplay:true,
        slidesToShow:3,
        slidesToSceool:1,
        prevArrow:".prev-btn",
        nextArrow:".next-btn"
    });
})